release:
  tag: latest
services:
  rearc-quest:
    type: LoadBalancer
    ports:
      - port: 80
        protocol: TCP
        targetPort: 3000
        name: rearc-quest
deployments:
  rearc-quest:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 10%
    replicaCount: 1
    containers:
      rearc-quest:
        image: johndodson85/rearc-quest:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
        args:
          - -c
          - node src/000.js
        containerPorts:
          - name: rearc-quest
            containerPort: 3000
            protocol: TCP
