name: "Terraform Apply"

on:
  workflow_run:
    workflows: [Docker Build]
    types:
      - completed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: rearc-quest

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r terraform/aws/${{ github.sha }}.zip src bin node_modules package.json

      - name: Apply AWS
        uses: dflook/terraform-apply@v1
        id: apply-aws
        with:
          auto_approve: true
          path: "./terraform"
          workspace: "rearc-quest"
          target: |
            module.aws
          variables: |
            last_run_commit = "${{ github.sha }}"
      
      - name: Apply Helm
        uses: dflook/terraform-apply@v1
        id: apply-helm
        with:
          auto_approve: true
          path: "./terraform"
          workspace: "rearc-quest"
          target: |
            module.helm
          variables: |
            last_run_commit = "${{ github.sha }}"
