name: "Terraform Apply"

on:
  workflow_run:
    workflows: [Docker Build]
    types:
      - completed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: rearc-quest

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply EKS
        uses: dflook/terraform-apply@v1
        id: apply-eks
        with:
          auto_approve: true
          path: "./terraform"
          workspace: "rearc-quest"
          variables: |
            chart_root = ${{ github.workspace }}/helm
          target: |
            module.eks
      
      - name: Apply Helm
        uses: dflook/terraform-apply@v1
        id: apply-helm
        with:
          auto_approve: true
          path: "./terraform"
          workspace: "rearc-quest"
          variables: |
            chart_root = ${{ github.workspace }}/helm
          target: |
            module.helm
